apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-mysql
  labels:
    app: webook-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webook-mysql
  template:
    metadata:
      name: webook-mysql
      labels:
        app: webook-mysql
    spec:
      containers:
        - name: webook-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          imagePullPolicy: IfNotPresent
          # 用的pod的哪一个volume
#          volumeDevices:
#            # 要对应到 mysql 的数据存储的位置
#            # 可以通过 mysql 的配置可以改这个目录
#            - devicePath: /var/lib/mysql
#              # 与下面1匹配
#              name: mysql-storage
          ports:
            - containerPort: 3306
      restartPolicy: Always
      # 声明pod有多少个持久化卷
#      volumes:
#        # 1
#        - name: mysql-storage
#          persistentVolumeClaim:
#            claimName: webook-mysql-claim