apiVersion: v1
kind: Service
metadata:
  name: webook-homework
spec:
  # 负载均衡器 
  type: LoadBalancer
  selector:
    app: webook-homework
  ports:
    - protocol: TCP
      port: 81
      # 1. 启动端口从 8080 修改成 8081
      targetPort: 8081
